- name: mariadb installation
  yum: pkg={{ item }}
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python

- name: starting mariadb
  service: name=mariadb state=started enabled=yes

- name: configuration mariadb
  mysql_db:
    name: "{{ database_name }}"
    state: present

- name: creating user
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: '*.*:ALL'
    state: present




